import { Button, CheckBox, ComboBox, VerticalBox, Slider, StandardListView, Switch } from "std-widgets.slint";

export component PlotWindow inherits Window {
    in property <string> window_title;
    in property <int> idx_ant;

    in property <string> h5parm;
    in property <string> solset;
    in property <string> soltab;
    title: window_title;
    min-width: 512px;
    min-height: 512px;

    pure callback render_plot(int, string, string, string, int, int) -> image;

    VerticalLayout {
        padding: 5px;
        Image {
            height: 85%;
            width: 100%;
            source: render_plot(idx_ant, h5parm, solset, soltab, parent.width/1px, parent.height/1px);
        }
        GridLayout {
            height: 5%;
            Button {
                col: 0;
                row: 0;
                text: "Prev.";
            }
            Text {
                col: 1;
                row: 0;
                colspan: 4;
                text: "Correlation: XX";
                horizontal-alignment: center;
                vertical-alignment: center;
            }
            //Slider {
            //    col: 1;
            //    row: 1;
            //    colspan: 4;
            //}
            Button {
                col: 5;
                row: 0;
                text: "Next";
            }
        }
        GridLayout{
            height: 10%;
            Button {
                col: 0;
                row: 0;
                text: "Previous antenna";
            }
            Button {
                col: 1;
                row: 0;
                text: "Next antenna";
            }
            Button {
                col: 2;
                row: 0;
                text: "Previous direction";
            }
            Button {
                col: 3;
                row: 0;
                text: "Next direction";
            }
        }
    }
}

export component AppWindow inherits Window {
    title: "LOFAR H5plot";
    min-width: 400px;
    min-height: 635px;
    default-font-family: "JetBrains Mono";
    default-font-size: 10pt;

    in-out property <StandardListViewItem> current_antenna;
    in-out property <int> current_antenna_idx;

    in property <[StandardListViewItem]> station_list;
    in property <[string]> solset_list;
    in property <[string]> soltab_list;
    in property <[string]> dir_list;
    in property <[string]> refant_list;

    in property <string> h5parm;
    in-out property <string> solset;
    in-out property <string> soltab;

    callback plot();
    callback update_antenna(int);

    popup := PopupWindow {
        Rectangle { height:100%; width: 100%; background: yellow; }
        x: 20px; y: 20px; height: 50px; width: 50px;
    }

    VerticalLayout {
        padding: 5px;
        GridLayout {
            height: 30pt;
            Row {
                Text {
                    text: "Solset";
                    vertical-alignment: center;
                    horizontal-alignment: center;
                    col: 0;
                }
                solsetPicker := ComboBox {
                    col: 1;
                    model: solset_list;
                    selected => {
                        solset = self.current-value;
                    }
                }
            }
        }
        GridLayout {
            height: 30pt;
            Row {
                HorizontalLayout {
                    Text {
                        text: "Soltab";
                        vertical-alignment: center;
                    }
                    ComboBox {
                        model: soltab_list;
                        selected => {
                            soltab = self.current-value;
                        }
                    }
                    Text {
                        text: "vs";
                        vertical-alignment: center;
                        horizontal-alignment: center;
                    }
                    ComboBox {
                        model: ["time", "frequency", "waterfall"];
                    }
                }
            }
        }
        GridLayout {
            height: 30pt;
            Row {
                HorizontalLayout {
                    Text {
                        text: "Ref. ant.";
                        vertical-alignment: center;
                    }
                    ComboBox {
                        model: refant_list;
                    }
                    Text {
                        text: "Dir.";
                        vertical-alignment: center;
                        horizontal-alignment: center;
                    }
                    ComboBox {
                        model: dir_list;
                    }
                }
            }
        }
        GridLayout {
            height: 60pt;
            Row {
                GridLayout {
                    Row {
                        Switch {
                            col: 0;
                            text: "Plot weights";
                        }
                        CheckBox {
                            col: 1;
                            text: "Time diff.";
                        }
                    }
                    Row {
                        CheckBox {
                            col: 0;
                            text: "Pol. diff. (XX - YY)";
                        }
                        CheckBox {
                            col: 1;
                            text: "Frequency diff.";
                        }
                    }
                }
            }
        }
        Button {
            width: 100%;
            height: 30pt;
            text: "Plot";
            clicked => {
                root.plot();
            }
        }
        Button {
            width: 100%;
            height: 30pt;
            text: "Plot all stations";
        }
        Text {
            height: 15pt;
            padding-bottom: 0;
            text: "Stations:";
            vertical-alignment: center;
        }
        StandardListView {
            width: 100%;
            model: station_list;
            current-item: 0;
            current-item-changed => {
                current_antenna = station_list[self.current-item];
                current_antenna_idx = self.current-item;
            }
        }
    }
}

